---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations: 
    cert-manager.io/inject-ca-from: openapioperator-system/webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-openapi-openapis-org-v1alpha1-openapispec
  failurePolicy: Fail
  name: mopenapispec-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openapi.openapis.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openapispecs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations: 
    cert-manager.io/inject-ca-from: openapioperator-system/webhook-server-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-openapi-openapis-org-v1alpha1-openapispec
  failurePolicy: Fail
  name: vopenapispec-v1alpha1.kb.io
  rules:
  - apiGroups:
    - openapi.openapis.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - openapispecs
  sideEffects: None
