# This rule is not used by the project openapioperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the openapi.openapis.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openapioperator
    app.kubernetes.io/managed-by: kustomize
  name: openapispec-editor-role
rules:
- apiGroups:
  - openapi.openapis.org
  resources:
  - openapispecs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openapi.openapis.org
  resources:
  - openapispecs/status
  verbs:
  - get
