---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openapi.openapis.org
  resources:
  - openapirouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openapi.openapis.org
  resources:
  - openapirouters/finalizers
  verbs:
  - update
- apiGroups:
  - openapi.openapis.org
  resources:
  - openapirouters/status
  verbs:
  - get
  - patch
  - update
